name: Docker
on:
  release:
    types: [published]
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        # v3.1.2
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v1.13.1'

      - name: Set up QEMU for ARM emulation
        # v2.2.0
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        # 2.10.0
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        # 2.2.0
        uses: docker/login-action@v2
        with:
          username: marcobaobao
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Generate Docker metadata
        id: meta
        # v4.6.0
        uses: docker/metadata-action@v4
        with:
          images: docker.io/marcobaobao/pdf-convert-microservice
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        id: build-and-push
        # v4.2.1
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign docker.io/marcobaobao/pdf-convert-microservice@${{ steps.build-and-push.outputs.digest }}
